---
version: '3.4'

networks:
  bitcoin-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.32.172.0/24"

services:
  tor:
    user: "${UID}:${GID}"
    build: 
      context: ./tor
      args:
        UID: "${UID}"
        GID: "${GID}"
    image: tor
    container_name: tor
    restart: unless-stopped
    networks:
      - bitcoin-network
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./tor/data:/tor/data
    expose:
      - 8332
      - 50001
      - 50002
      - 9050
    ports:
      - 8332:8332
      - 50001:50001
      - 50002:50002

  bitcoin-core:
    user: "${UID}:${GID}"
    build: 
      context: ./bitcoin-core
      args:
        UID: "${UID}"
        GID: "${GID}"
    network_mode: service:tor
    image: bitcoin-core
    container_name: bitcoin-core
    volumes:
      - ./bitcoin-core/data/:/home/bitcoin/.bitcoin
      - ./bitcoin-core/bitcoin.conf:/home/bitcoin/bitcoin.conf
    restart: unless-stopped
    depends_on:
      - tor

  electrs:
    user: "${UID}:${GID}"
    build: 
      context: ./electrs
      args:
        UID: "${UID}"
        GID: "${GID}"
    network_mode: service:tor
    image: electrs
    container_name: electrs
    volumes:
      - ./electrs/data:/db
      - ./bitcoin-core/data/:/home/electrs/.bitcoin
    environment:
      ELECTRUM_RPC_ADDR: "127.0.0.1:50002"
    restart: always
    depends_on:
      - bitcoin-core
      - tor
